name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Mise à jour de la version de Node.js

      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --configuration=production --base-href=/kooler-portfolio/ --output-path=dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PORTFOLIO_TOKEN }}
          publish_dir: ./dist/browser # Le répertoire racine est spécifié ici